# Generated by Django 2.1.1 on 2019-01-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('width', models.IntegerField(default=382)),
                ('height', models.IntegerField(default=681)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
