# Generated by Django 2.1.4 on 2018-12-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendIndexHtml', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
