# Generated by Django 2.1.4 on 2018-12-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(max_length=2000),
        ),
    ]
